// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rmwxggclwjwcnjyrqckt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtd3hnZ2Nsd2p3Y25qeXJxY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3ODMzNjYsImV4cCI6MjA5MjM1OTM2Nn0.-XW9O9X9yLhqGY5W81T8lFETCCECnRCsS_l8gSdvas4";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);