// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://avcrvmlemjpmijotxixt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_G2p-LAMgOcRjF3dIRvVMLQ_Begb8hdZ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);